### ISSUE TITLE
Strange NullPointerException 

### ISSUE THREAD

**Issue by mr-procrastinator** [x2on/gradle-hockeyapp-plugin#47]
Hi guys, 
I've faced with problem during uploading of the my apps. 
I have several app targets, to upload all together I am using gradle task like following:
`task uploadApps(dependsOn: [':app:assembleTarget1', ':app:assembleTarget2', ':app:assembleTarget3']) << {
    uploadTarget1ToHockeyApp.execute()
    uploadTarget2ToHockeyApp.execute()
    uploadTarget3ToHockeyApp.execute()
}`
On version 2.0, all was working fine. 
After updating to version 2.4. Uploading of multiple targets process failed in the one of task with NullPointerEcxeption:
 `   Caused by: java.lang.NullPointerException
        at java_util_regex_Pattern$compile.call(Unknown Source)
        at de.felixschulze.gradle.HockeyAppUploadTask.getFile(HockeyAppUploadTask.groovy:285)
        at de.felixschulze.gradle.HockeyAppUploadTask$getFile$1.callStatic(Unknown Source)
        at de.felixschulze.gradle.HockeyAppUploadTask.upload(HockeyAppUploadTask.groovy:72)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 49 more  `
But when I am trying upload this target standalone by using *uploadTarget3ToHockeyApp* all is working fine. 

On version 2.6 I had following error:
`Caused by: java.lang.IllegalArgumentException: No applicationFile found or no appFileNameRegex provided.
        at de.felixschulze.gradle.HockeyAppUploadTask.upload(HockeyAppUploadTask.groovy:95)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)`

Do you have any thoughts about reasons of this issue?

**Comment by mr-procrastinator** [comment]
I've fixed the issue, the problems was in task wrong dependencies between gradle tasks.
