### ISSUE TITLE
Unable to determine the current character, it is not a string, number, array, or object

### ISSUE THREAD

**Issue by bartoszkopinski** [x2on/gradle-hockeyapp-plugin#52]
Hi @x2on,
I'm getting this exception when running `./gradlew uploadStagingReleaseToHockeyApp`:

```shell
[org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:uploadStagingReleaseToHockeyApp'.
[org.gradle.api.Task] App file: /Users/user/Android/project-android/app/build/outputs/apk/app-staging-release-unsigned.apk
[org.gradle.api.Task] Will upload to: https://rink.hockeyapp.net/api/2/apps/co.company.project.project.staging/app_versions/upload
[org.gradle.api.Task] Request: POST https://rink.hockeyapp.net/api/2/apps/co.company.project.project.staging/app_versions/upload HTTP/1.1
[org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
[org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
[org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {s}->https://rink.hockeyapp.net:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
[org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 0][route: {s}->https://rink.hockeyapp.net:443][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
[org.apache.http.impl.execchain.MainClientExec] Opening connection {s}->https://rink.hockeyapp.net:443
[org.apache.http.impl.conn.HttpClientConnectionOperator] Connecting to rink.hockeyapp.net/23.23.238.220:443
[org.apache.http.impl.conn.HttpClientConnectionOperator] Connection established 10.0.1.3:57105<->23.23.238.220:443
[org.apache.http.impl.execchain.MainClientExec] Executing request POST /api/2/apps/co.company.project.project.staging/app_versions/upload HTTP/1.1
[org.apache.http.impl.execchain.MainClientExec] Target auth state: UNCHALLENGED
[org.apache.http.impl.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
[org.apache.http.headers] http-outgoing-0 >> POST /api/2/apps/co.company.project.project.staging/app_versions/upload HTTP/1.1
[org.apache.http.headers] http-outgoing-0 >> X-HockeyAppToken: [token]
[org.apache.http.headers] http-outgoing-0 >> Content-Length: 2979744
[org.apache.http.headers] http-outgoing-0 >> Content-Type: multipart/form-data; boundary=pwLl-KcFRdUQh-LsaRG4Ck1HOBjnQmRDR5xM
[org.apache.http.headers] http-outgoing-0 >> Host: rink.hockeyapp.net
[org.apache.http.headers] http-outgoing-0 >> Connection: Keep-Alive
[org.apache.http.headers] http-outgoing-0 >> User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
[org.apache.http.headers] http-outgoing-0 >> Accept-Encoding: gzip,deflate
[org.gradle.api.Task] 5% uploaded
[org.gradle.api.Task] 10% uploaded
[org.gradle.api.Task] 15% uploaded
[org.gradle.api.Task] 20% uploaded
[org.gradle.api.Task] 25% uploaded
[org.gradle.api.Task] 30% uploaded
[org.gradle.api.Task] 35% uploaded
[org.gradle.api.Task] 40% uploaded
[org.gradle.api.Task] 45% uploaded
[org.gradle.api.Task] 50% uploaded
[org.gradle.api.Task] 55% uploaded
[org.gradle.api.Task] 60% uploaded
[org.gradle.api.Task] 65% uploaded
[org.gradle.api.Task] 70% uploaded
[org.gradle.api.Task] 75% uploaded
[org.gradle.api.Task] 80% uploaded
[org.gradle.api.Task] 85% uploaded
[org.gradle.api.Task] 90% uploaded
[org.gradle.api.Task] 95% uploaded
[org.gradle.api.Task] 100% uploaded
[org.apache.http.headers] http-outgoing-0 << HTTP/1.1 200 OK
[org.apache.http.headers] http-outgoing-0 << Cache-Control: max-age=0, private, must-revalidate
[org.apache.http.headers] http-outgoing-0 << Content-Security-Policy: frame-ancestors https://rink.hockeyapp.net http://hockeyapp.net http://hockeyapp.com
[org.apache.http.headers] http-outgoing-0 << Content-Type: text/html; charset=utf-8
[org.apache.http.headers] http-outgoing-0 << Date: Tue, 24 Feb 2015 21:31:27 GMT
[org.apache.http.headers] http-outgoing-0 << ETag: "7215ee9c7d9dc229d2921a40e899ec5f"
[org.apache.http.headers] http-outgoing-0 << Server: nginx
[org.apache.http.headers] http-outgoing-0 << Set-Cookie: request_method=POST; path=/
[org.apache.http.headers] http-outgoing-0 << Status: 200 OK
[org.apache.http.headers] http-outgoing-0 << X-Rack-Cache: invalidate, pass
[org.apache.http.headers] http-outgoing-0 << X-Request-Id: 0586e3147e26107c96bec8a52ecaf95b
[org.apache.http.headers] http-outgoing-0 << X-Runtime: 0.010768
[org.apache.http.headers] http-outgoing-0 << X-UA-Compatible: IE=Edge,chrome=1
[org.apache.http.headers] http-outgoing-0 << Content-Length: 1
[org.apache.http.headers] http-outgoing-0 << Connection: keep-alive
[org.apache.http.impl.execchain.MainClientExec] Connection can be kept alive indefinitely
[org.apache.http.client.protocol.ResponseProcessCookies] Cookie accepted [request_method="POST", version:0, domain:rink.hockeyapp.net, path:/, expiry:null]
[org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection [id: 0][route: {s}->https://rink.hockeyapp.net:443] can be kept alive indefinitely
[org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 0][route: {s}->https://rink.hockeyapp.net:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
[org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:uploadStagingReleaseToHockeyApp'
[org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:uploadStagingReleaseToHockeyApp (Thread[main,5,main]) completed. Took 13.939 secs.
[org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 21.78 secs, idle: 0.058 secs
[org.gradle.BuildExceptionReporter]
[org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
[org.gradle.BuildExceptionReporter]
[org.gradle.BuildExceptionReporter] * What went wrong:
[org.gradle.BuildExceptionReporter] Execution failed for task ':app:uploadStagingReleaseToHockeyApp'.
[org.gradle.BuildExceptionReporter] > Unable to determine the current character, it is not a string, number, array, or object
[org.gradle.BuildExceptionReporter]
[org.gradle.BuildExceptionReporter]   The current character read is '' with an int value of 0
[org.gradle.BuildExceptionReporter]   Unable to determine the current character, it is not a string, number, array, or object
[org.gradle.BuildExceptionReporter]   line number 1
[org.gradle.BuildExceptionReporter]   index number 255
[org.gradle.BuildExceptionReporter]
[org.gradle.BuildExceptionReporter]   ...............................................................................................................................................................................................................................................................^
[org.gradle.BuildExceptionReporter]
[org.gradle.BuildExceptionReporter] * Exception is:
[org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:uploadStagingReleaseToHockeyApp'.
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
[org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
[org.gradle.BuildExceptionReporter]  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
[org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
[org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
[org.gradle.BuildExceptionReporter]  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
[org.gradle.BuildExceptionReporter]  at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.Main.doAction(Main.java:33)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
[org.gradle.BuildExceptionReporter]  at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
[org.gradle.BuildExceptionReporter]  at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
[org.gradle.BuildExceptionReporter]  at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
[org.gradle.BuildExceptionReporter]  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
```

This is my `build.gradle`:
```groovy
apply plugin: 'com.android.application'
apply plugin: 'de.felixschulze.gradle.hockeyapp'

hockeyapp {
    apiToken = "token"
    notify = 1
    status = 2
    notesType = 1
    notes = "Some notes."
    variantToReleaseType = [
        stagingRelease: 0,
        productionRelease: 1
    ]
    variantToApplicationId = [
        stagingRelease: "co.company.project.project.staging",
        productionRelease: "co.company.project.project",
    ]
}

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }

    productFlavors {
        staging {
            applicationId 'co.company.project.project.staging'
        }

        production {
            applicationId 'co.company.project.project'
        }

        development {
            applicationId 'co.company.project.project'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'net.hockeyapp.android:HockeySDK:2.2.1'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.google.code.gson:gson:1.7.2'
    compile 'com.jakewharton:butterknife:6.1.0'
    compile 'com.walnutlabs:androidprogresshud:1.0'
}
```

Do you, by any chance, know what might be the problem?

**Comment by x2on** [comment]
Is the new version available in HockeyApp after executing the task?

**Comment by x2on** [comment]
Could be related to https://github.com/x2on/gradle-spoon-plugin/issues

Do you use any Proxy or similar technics?

**Comment by x2on** [comment]
So my question: Which gradle version you are using?

**Comment by bartoszkopinski** [comment]
Thanks for the reply. 
There's no new version in Hockey although it seems to be uploaded successfully. 
I'm using Gradle 2.2.1, it fails both locally and using circleci.com

**Comment by x2on** [comment]
Could you please try to run with `--stacktrace`?

I think HockeyApp returns an error, which causes the `JsonSlurp` to fail.

And please double check if your application id's are correct.

**Comment by x2on** [comment]
Ok now i think i got the error: In `variantToApplicationId` you have to enter the hockey app id, not your bundle identifier.

With that change it should work.

But i will add more verbose error handling for sure :)

**Comment by bartoszkopinski** [comment]
Thank you! That was it.
A small note in readme will be helpful as well.

**Comment by x2on** [comment]
I added better error output in the 3.1 release. Thanks for submitting this bug.
