### ISSUE TITLE
Crash java.lang.NoSuchFieldError: INSTANCE when trying to upload an apk 

### ISSUE THREAD

**Issue by chemouna** [x2on/gradle-hockeyapp-plugin#79]
Thanks for the plugin.

I'm trying to use it to upload to hockeyapp but everytime i run 
` # ../gradlew uploadDefaultConfigDebugToHockeyApp --stacktrace --debug
`
i get : 

```
17:53:29.075 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':example:uploadDefaultConfigDebugToHockeyApp'.
17:53:29.076 [DEBUG] [org.gradle.api.Task] Using android application variants
17:53:29.086 [DEBUG] [org.gradle.api.Task] Obfuscation is not used
17:53:29.087 [LIFECYCLE] [org.gradle.api.Task] App file: /Users/user/repos/workspace/Example/build/outputs/apk/Example-defaultConfig-debug-unaligned.apk
17:53:29.270 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':Example:uploadDefaultConfigDebugToHockeyApp'
17:53:29.271 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :Example:uploadDefaultConfigDebugToHockeyApp FAILED
17:53:29.271 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :Example:uploadDefaultConfigDebugToHockeyApp (Thread[main,5,main]) completed. Took 0.197 secs.
17:53:29.271 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 19.596 secs, idle: 0.023 secs
17:53:29.279 [ERROR] [org.gradle.BuildExceptionReporter] 
17:53:29.281 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:53:29.284 [ERROR] [org.gradle.BuildExceptionReporter] 
17:53:29.284 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:53:29.284 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':Example:uploadDefaultConfigDebugToHockeyApp'.
17:53:29.285 [ERROR] [org.gradle.BuildExceptionReporter] > INSTANCE
17:53:29.285 [ERROR] [org.gradle.BuildExceptionReporter] 
17:53:29.285 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
17:53:29.287 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':example:uploadDefaultConfigDebugToHockeyApp'.
17:53:29.287 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
17:53:29.287 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
17:53:29.287 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
17:53:29.287 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
17:53:29.287 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
17:53:29.287 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
17:53:29.287 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
17:53:29.288 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
17:53:29.289 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
17:53:29.290 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.Main.doAction(Main.java:33)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoSuchFieldError: INSTANCE
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:72)
17:53:29.291 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:84)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:59)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:494)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:726)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.apache.http.impl.client.HttpClientBuilder$build$1.call(Unknown Source)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at de.felixschulze.gradle.HockeyAppUploadTask.uploadAppplicationFileToHockeyApp(HockeyAppUploadTask.groovy:169)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at de.felixschulze.gradle.HockeyAppUploadTask$uploadAppplicationFileToHockeyApp.callCurrent(Unknown Source)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at de.felixschulze.gradle.HockeyAppUploadTask.upload(HockeyAppUploadTask.groovy:144)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
17:53:29.292 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
17:53:29.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
17:53:29.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
17:53:29.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
17:53:29.293 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
17:53:29.293 [ERROR] [org.gradle.BuildExceptionReporter]        ... 60 more
17:53:29.293 [ERROR] [org.gradle.BuildExceptionReporter] 
17:53:29.293 [LIFECYCLE] [org.gradle.BuildResultLogger] 
17:53:29.293 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
17:53:29.293 [LIFECYCLE] [org.gradle.BuildResultLogger] 
17:53:29.293 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 2 mins 14.677 secs
```

i did what's being said in the README.md to move plugin classpath to root build.gradle file but still the same problem.

here's the config i'm using : 

```
apply plugin: 'de.felixschulze.gradle.hockeyapp'
hockeyapp {
    apiToken = "1234567"
    releaseType = 0
    notify = 0
    status = 2
    variantToApplicationId = [
            defaultConfigDebug: "12345678",
            DefaultConfig: "12345678"
    ] //i'm not sure if the way im setting defaultconfig here is correct ?
}
```

**Comment by abusuioc** [comment]
solution here: [https://github.com/x2on/gradle-hockeyapp-plugin/issues/30](https://github.com/x2on/gradle-hockeyapp-plugin/issues/30)
