### ISSUE TITLE
SocketException: Permission denied: connect

### ISSUE THREAD

**Issue by eugene-petriyov** [x2on/gradle-hockeyapp-plugin#98]
I try to publish my apk to HockeyApp using API_TOKEN with FULL_ACCESS and i get:
Caused by: java.net.SocketException: Permission denied: connect
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSL
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClie
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttp
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttp
        at org.apache.http.client.HttpClient$execute.call(Unknown Source)
        at de.felixschulze.gradle.HockeyAppUploadTask.uploadFilesToHockeyApp(Hoc
        at de.felixschulze.gradle.HockeyAppUploadTask$uploadFilesToHockeyApp.cal
        at de.felixschulze.gradle.HockeyAppUploadTask.upload(HockeyAppUploadTask
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)

Is it the plugin bug or problems with permissions access

**Comment by x2on** [comment]
Looks like a problem with permissions
